/**
 * Mock data for admin console development.
 * In production, all data comes from API endpoints.
 */

import type { AdminUser } from './types/auth';
import type { PolicyRule } from './types/policies';
import type { ApprovalRequest, ApprovalStats } from './types/approvals';
import type { AuditEntry, DeviceHealth } from './types/audit';
import type { SharedConnection, SyncTemplate, Workspace } from './types/workspaces';

// ---- Mock Users ----
export const mockUsers: AdminUser[] = [
  {
    id: 'usr_001',
    email: 'owner@acme.com',
    name: 'Alice Johnson',
    role: 'org_owner',
    permissions: [],
    organizationId: 'org_001',
    lastLoginAt: '2026-03-15T09:30:00Z',
    createdAt: '2025-01-15T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_002',
    email: 'admin@acme.com',
    name: 'Bob Smith',
    role: 'org_admin',
    permissions: [],
    organizationId: 'org_001',
    lastLoginAt: '2026-03-14T14:22:00Z',
    createdAt: '2025-02-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_003',
    email: 'security@acme.com',
    name: 'Carol Davis',
    role: 'security_admin',
    permissions: [],
    organizationId: 'org_001',
    lastLoginAt: '2026-03-15T08:45:00Z',
    createdAt: '2025-02-15T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_004',
    email: 'approver@acme.com',
    name: 'Dan Wilson',
    role: 'approver',
    permissions: [],
    organizationId: 'org_001',
    lastLoginAt: '2026-03-13T16:00:00Z',
    createdAt: '2025-03-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_005',
    email: 'operator@acme.com',
    name: 'Eve Martinez',
    role: 'operator',
    permissions: [],
    organizationId: 'org_001',
    lastLoginAt: '2026-03-15T10:15:00Z',
    createdAt: '2025-03-15T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_006',
    email: 'user@acme.com',
    name: 'Frank Lee',
    role: 'user',
    permissions: [],
    organizationId: 'org_001',
    createdAt: '2025-04-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_007',
    email: 'auditor@acme.com',
    name: 'Grace Kim',
    role: 'read_only_auditor',
    permissions: [],
    organizationId: 'org_001',
    lastLoginAt: '2026-03-14T11:30:00Z',
    createdAt: '2025-04-15T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_008',
    email: 'inactive@acme.com',
    name: 'Henry Brown',
    role: 'user',
    permissions: [],
    organizationId: 'org_001',
    createdAt: '2025-05-01T10:00:00Z',
    isActive: false,
  },
];

// ---- Mock Policies ----
export const mockPolicies: PolicyRule[] = [
  {
    id: 'pol_001',
    domain: 'encryption_requirements',
    name: 'Organization Encryption Policy',
    description: 'All data must be encrypted at rest and in transit',
    assignmentTarget: 'org',
    assignmentValue: 'org_001',
    enforcementMode: 'enforce',
    configuration: { atRest: true, inTransit: true, algorithm: 'AES-256', keyRotationDays: 90 },
    createdBy: 'usr_001',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
    version: 1,
    isActive: true,
  },
  {
    id: 'pol_002',
    domain: 'max_transfer_size',
    name: 'Standard Transfer Limits',
    description: 'Default transfer size limits for all users',
    assignmentTarget: 'org',
    assignmentValue: 'org_001',
    enforcementMode: 'enforce',
    configuration: { maxFileSizeMB: 500, maxBatchSizeMB: 5000, maxFileCount: 1000 },
    createdBy: 'usr_001',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
    version: 1,
    isActive: true,
  },
  {
    id: 'pol_003',
    domain: 'file_type_restrictions',
    name: 'Block Executable Files',
    description: 'Block executable file transfers for security',
    assignmentTarget: 'org',
    assignmentValue: 'org_001',
    enforcementMode: 'enforce',
    configuration: { mode: 'blocklist', extensions: ['.exe', '.bat', '.cmd', '.msi', '.scr'], mimeTypes: [] },
    createdBy: 'usr_003',
    createdAt: '2025-07-01T10:00:00Z',
    updatedAt: '2025-07-01T10:00:00Z',
    version: 1,
    isActive: true,
  },
  {
    id: 'pol_004',
    domain: 'allowed_connectors',
    name: 'Approved Cloud Services',
    description: 'Only approved cloud storage services can be used',
    assignmentTarget: 'org',
    assignmentValue: 'org_001',
    enforcementMode: 'enforce',
    configuration: { allowed: ['s3', 'azure_blob', 'gcs', 'sftp'], blocked: ['ftp', 'webdav_unencrypted'] },
    createdBy: 'usr_003',
    createdAt: '2025-07-15T10:00:00Z',
    updatedAt: '2025-07-15T10:00:00Z',
    version: 1,
    isActive: true,
  },
  {
    id: 'pol_005',
    domain: 'ai_usage',
    name: 'AI Data Processing Policy',
    description: 'Control how AI features can process organizational data',
    assignmentTarget: 'org',
    assignmentValue: 'org_001',
    enforcementMode: 'enforce',
    configuration: { allowClassification: true, allowContentAnalysis: false, allowNamingSuggestions: true, dataResidency: 'local', excludedPaths: ['/confidential', '/legal'] },
    createdBy: 'usr_001',
    createdAt: '2025-08-01T10:00:00Z',
    updatedAt: '2025-08-01T10:00:00Z',
    version: 1,
    isActive: true,
  },
  {
    id: 'pol_006',
    domain: 'retention',
    name: 'Default Retention Policy',
    description: '90-day retention with auto-archive',
    assignmentTarget: 'org',
    assignmentValue: 'org_001',
    enforcementMode: 'enforce',
    configuration: { defaultRetentionDays: 90, archiveAfterDays: 60, autoDeleteAfterDays: 365, excludedPaths: ['/permanent'] },
    createdBy: 'usr_001',
    createdAt: '2025-08-15T10:00:00Z',
    updatedAt: '2025-08-15T10:00:00Z',
    version: 1,
    isActive: true,
  },
  {
    id: 'pol_007',
    domain: 'naming_strictness',
    name: 'Strict Naming for Legal Team',
    description: 'Tier 3 naming conventions for the legal role',
    assignmentTarget: 'role',
    assignmentValue: 'approver',
    enforcementMode: 'enforce',
    configuration: { enforceConventions: true, allowedPatterns: ['^[A-Z]{3}-\\d{4}-.*$'], maxLength: 128, disallowSpecialChars: true, tier: 3 },
    createdBy: 'usr_003',
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-09-01T10:00:00Z',
    version: 1,
    isActive: true,
  },
];

// ---- Mock Approval Requests ----
export const mockApprovals: ApprovalRequest[] = [
  {
    id: 'apr_001',
    operation: 'File Transfer',
    trigger: 'external_dest_transfer',
    source: 'S3: acme-internal',
    destination: 'External SFTP: partner-uploads',
    fileCount: 15,
    totalSize: 2_500_000_000,
    reason: 'Quarterly report delivery to external partner',
    triggeringPolicy: 'Approved Destinations Policy',
    state: 'pending',
    requestedBy: 'usr_005',
    requestedByName: 'Eve Martinez',
    requestedAt: '2026-03-15T08:30:00Z',
    expiresAt: '2026-03-17T08:30:00Z',
    organizationId: 'org_001',
  },
  {
    id: 'apr_002',
    operation: 'Destructive Sync',
    trigger: 'destructive_sync',
    source: 'Azure Blob: project-archive',
    destination: 'Local: /data/archive',
    fileCount: 1200,
    totalSize: 50_000_000_000,
    reason: 'Archive cleanup - removing outdated project files',
    triggeringPolicy: 'Deletion Restrictions Policy',
    state: 'pending',
    requestedBy: 'usr_002',
    requestedByName: 'Bob Smith',
    requestedAt: '2026-03-14T16:45:00Z',
    expiresAt: '2026-03-16T16:45:00Z',
    organizationId: 'org_001',
  },
  {
    id: 'apr_003',
    operation: 'Policy Exception',
    trigger: 'policy_exception',
    source: 'GCS: dev-assets',
    destination: 'S3: staging-assets',
    fileCount: 3,
    totalSize: 150_000_000,
    reason: 'Need to transfer .exe installer for internal deployment',
    triggeringPolicy: 'Block Executable Files',
    state: 'approved',
    requestedBy: 'usr_005',
    requestedByName: 'Eve Martinez',
    requestedAt: '2026-03-13T10:00:00Z',
    expiresAt: '2026-03-15T10:00:00Z',
    reviewedBy: 'usr_004',
    reviewedByName: 'Dan Wilson',
    reviewedAt: '2026-03-13T11:30:00Z',
    reviewComment: 'Approved for internal deployment purposes only',
    organizationId: 'org_001',
  },
  {
    id: 'apr_004',
    operation: 'Sensitive File Transfer',
    trigger: 'sensitive_file',
    source: 'Local: /legal/contracts',
    destination: 'SFTP: external-counsel',
    fileCount: 5,
    totalSize: 25_000_000,
    reason: 'Legal review by external counsel',
    triggeringPolicy: 'AI Data Processing Policy',
    state: 'denied',
    requestedBy: 'usr_006',
    requestedByName: 'Frank Lee',
    requestedAt: '2026-03-12T09:00:00Z',
    expiresAt: '2026-03-14T09:00:00Z',
    reviewedBy: 'usr_003',
    reviewedByName: 'Carol Davis',
    reviewedAt: '2026-03-12T14:00:00Z',
    reviewComment: 'External counsel should use the secure portal instead',
    organizationId: 'org_001',
  },
  {
    id: 'apr_005',
    operation: 'Tier 3 Naming Override',
    trigger: 'tier3_naming',
    source: 'Local: /documents',
    destination: 'S3: legal-docs',
    fileCount: 1,
    totalSize: 500_000,
    reason: 'Legacy file name does not match Tier 3 pattern',
    triggeringPolicy: 'Strict Naming for Legal Team',
    state: 'expired',
    requestedBy: 'usr_006',
    requestedByName: 'Frank Lee',
    requestedAt: '2026-03-10T08:00:00Z',
    expiresAt: '2026-03-12T08:00:00Z',
    organizationId: 'org_001',
  },
];

export const mockApprovalStats: ApprovalStats = {
  pending: 2,
  approvedToday: 1,
  deniedToday: 0,
  expiredToday: 0,
  averageResponseTimeMinutes: 95,
};

// ---- Mock Audit Entries ----
export const mockAuditEntries: AuditEntry[] = [
  {
    id: 'aud_001',
    eventType: 'auth.login',
    severity: 'info',
    timestamp: '2026-03-15T09:30:00Z',
    userId: 'usr_001',
    userName: 'Alice Johnson',
    userEmail: 'owner@acme.com',
    organizationId: 'org_001',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    description: 'User logged in successfully',
    metadata: { method: 'password', mfaUsed: true },
    integrityHash: 'a1b2c3d4e5f6...',
  },
  {
    id: 'aud_002',
    eventType: 'transfer.start',
    severity: 'info',
    timestamp: '2026-03-15T09:35:00Z',
    userId: 'usr_005',
    userName: 'Eve Martinez',
    userEmail: 'operator@acme.com',
    organizationId: 'org_001',
    ipAddress: '192.168.1.105',
    userAgent: 'UFOP Desktop/1.0.0 (Windows)',
    description: 'Started transfer of 15 files (2.5 GB) from S3 to SFTP',
    metadata: { fileCount: 15, totalSize: 2_500_000_000, source: 'S3', dest: 'SFTP' },
    resourceType: 'transfer',
    resourceId: 'txn_001',
    integrityHash: 'b2c3d4e5f6a1...',
    previousHash: 'a1b2c3d4e5f6...',
  },
  {
    id: 'aud_003',
    eventType: 'policy.violation',
    severity: 'warning',
    timestamp: '2026-03-15T09:40:00Z',
    userId: 'usr_006',
    userName: 'Frank Lee',
    userEmail: 'user@acme.com',
    organizationId: 'org_001',
    ipAddress: '192.168.1.106',
    userAgent: 'UFOP Desktop/1.0.0 (macOS)',
    description: 'Attempted to transfer blocked file type (.exe)',
    metadata: { policyId: 'pol_003', fileName: 'setup.exe', action: 'blocked' },
    resourceType: 'policy',
    resourceId: 'pol_003',
    integrityHash: 'c3d4e5f6a1b2...',
    previousHash: 'b2c3d4e5f6a1...',
  },
  {
    id: 'aud_004',
    eventType: 'approval.approve',
    severity: 'info',
    timestamp: '2026-03-13T11:30:00Z',
    userId: 'usr_004',
    userName: 'Dan Wilson',
    userEmail: 'approver@acme.com',
    organizationId: 'org_001',
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    description: 'Approved policy exception request for .exe transfer',
    metadata: { approvalId: 'apr_003', reason: 'Internal deployment' },
    resourceType: 'approval',
    resourceId: 'apr_003',
    integrityHash: 'd4e5f6a1b2c3...',
    previousHash: 'c3d4e5f6a1b2...',
  },
  {
    id: 'aud_005',
    eventType: 'admin.role_change',
    severity: 'warning',
    timestamp: '2026-03-12T15:00:00Z',
    userId: 'usr_001',
    userName: 'Alice Johnson',
    userEmail: 'owner@acme.com',
    organizationId: 'org_001',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    description: 'Changed role for Grace Kim from user to read_only_auditor',
    metadata: { targetUserId: 'usr_007', previousRole: 'user', newRole: 'read_only_auditor' },
    resourceType: 'user',
    resourceId: 'usr_007',
    integrityHash: 'e5f6a1b2c3d4...',
    previousHash: 'd4e5f6a1b2c3...',
  },
  {
    id: 'aud_006',
    eventType: 'sync.conflict',
    severity: 'warning',
    timestamp: '2026-03-15T10:20:00Z',
    userId: 'usr_005',
    userName: 'Eve Martinez',
    userEmail: 'operator@acme.com',
    organizationId: 'org_001',
    ipAddress: '192.168.1.105',
    userAgent: 'UFOP Desktop/1.0.0 (Windows)',
    description: 'Sync conflict detected: report-Q1.xlsx modified on both sides',
    metadata: { fileName: 'report-Q1.xlsx', resolution: 'newest_wins', localModified: '2026-03-15T10:15:00Z', remoteModified: '2026-03-15T10:18:00Z' },
    resourceType: 'sync',
    resourceId: 'sync_001',
    integrityHash: 'f6a1b2c3d4e5...',
    previousHash: 'e5f6a1b2c3d4...',
  },
];

// ---- Mock Device Health ----
export const mockDevices: DeviceHealth[] = [
  {
    id: 'dev_001',
    deviceId: 'device-abc-123',
    deviceName: 'Eve-Workstation',
    userId: 'usr_005',
    userName: 'Eve Martinez',
    clientVersion: '1.2.0',
    os: 'Windows',
    osVersion: '11 Pro 23H2',
    lastSeenAt: '2026-03-15T10:20:00Z',
    status: 'online',
    failurePatterns: [],
    policyCompliance: { isCompliant: true, violations: [], lastCheckedAt: '2026-03-15T10:00:00Z' },
    cpuUsage: 15,
    memoryUsage: 42,
    diskUsage: 65,
  },
  {
    id: 'dev_002',
    deviceId: 'device-def-456',
    deviceName: 'Bob-Laptop',
    userId: 'usr_002',
    userName: 'Bob Smith',
    clientVersion: '1.2.0',
    os: 'macOS',
    osVersion: '14.2',
    lastSeenAt: '2026-03-15T09:45:00Z',
    status: 'online',
    failurePatterns: [],
    policyCompliance: { isCompliant: true, violations: [], lastCheckedAt: '2026-03-15T09:30:00Z' },
    cpuUsage: 8,
    memoryUsage: 55,
    diskUsage: 40,
  },
  {
    id: 'dev_003',
    deviceId: 'device-ghi-789',
    deviceName: 'Frank-Desktop',
    userId: 'usr_006',
    userName: 'Frank Lee',
    clientVersion: '1.1.0',
    os: 'Windows',
    osVersion: '10 Pro 22H2',
    lastSeenAt: '2026-03-14T18:30:00Z',
    status: 'offline',
    failurePatterns: [
      { type: 'connection_timeout', count: 3, lastOccurrence: '2026-03-14T18:25:00Z', description: 'S3 connection timeouts' },
    ],
    policyCompliance: {
      isCompliant: false,
      violations: [
        { policyId: 'pol_version', policyName: 'Minimum Client Version', domain: 'allowed_connectors', description: 'Client version 1.1.0 is below minimum 1.2.0', severity: 'medium', detectedAt: '2026-03-14T12:00:00Z' },
      ],
      lastCheckedAt: '2026-03-14T18:00:00Z',
    },
    cpuUsage: 0,
    memoryUsage: 0,
    diskUsage: 78,
  },
  {
    id: 'dev_004',
    deviceId: 'device-jkl-012',
    deviceName: 'Carol-MacBook',
    userId: 'usr_003',
    userName: 'Carol Davis',
    clientVersion: '1.2.0',
    os: 'macOS',
    osVersion: '15.0',
    lastSeenAt: '2026-03-15T10:18:00Z',
    status: 'online',
    failurePatterns: [],
    policyCompliance: { isCompliant: true, violations: [], lastCheckedAt: '2026-03-15T10:15:00Z' },
    cpuUsage: 12,
    memoryUsage: 38,
    diskUsage: 52,
  },
  {
    id: 'dev_005',
    deviceId: 'device-mno-345',
    deviceName: 'Grace-Laptop',
    userId: 'usr_007',
    userName: 'Grace Kim',
    clientVersion: '1.2.0',
    os: 'Linux',
    osVersion: 'Ubuntu 24.04',
    lastSeenAt: '2026-03-15T07:00:00Z',
    status: 'degraded',
    failurePatterns: [
      { type: 'sync_error', count: 5, lastOccurrence: '2026-03-15T06:55:00Z', description: 'Intermittent sync failures with Azure Blob' },
    ],
    policyCompliance: { isCompliant: true, violations: [], lastCheckedAt: '2026-03-15T07:00:00Z' },
    cpuUsage: 45,
    memoryUsage: 82,
    diskUsage: 90,
  },
];

// ---- Mock Workspaces ----
export const mockWorkspaces: Workspace[] = [
  {
    id: 'ws_001',
    name: 'Engineering Team',
    description: 'Shared resources for the engineering department',
    organizationId: 'org_001',
    connections: [],
    syncTemplates: [],
    automationTemplates: [],
    members: [
      { userId: 'usr_002', userName: 'Bob Smith', userEmail: 'admin@acme.com', accessLevel: 'admin', addedAt: '2025-06-01T10:00:00Z', addedBy: 'usr_001' },
      { userId: 'usr_005', userName: 'Eve Martinez', userEmail: 'operator@acme.com', accessLevel: 'write', addedAt: '2025-06-01T10:00:00Z', addedBy: 'usr_001' },
      { userId: 'usr_006', userName: 'Frank Lee', userEmail: 'user@acme.com', accessLevel: 'read', addedAt: '2025-06-15T10:00:00Z', addedBy: 'usr_002' },
    ],
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
];

export const mockSharedConnections: SharedConnection[] = [
  {
    id: 'sc_001',
    name: 'Team S3 Bucket',
    connectorType: 's3',
    config: { bucket: 'acme-engineering', region: 'us-east-1' },
    ownerId: 'usr_002',
    ownerName: 'Bob Smith',
    organizationId: 'org_001',
    sharedWith: [
      { userId: 'usr_005', userName: 'Eve Martinez', userEmail: 'operator@acme.com', accessLevel: 'write', addedAt: '2025-06-01T10:00:00Z', addedBy: 'usr_002' },
      { userId: 'usr_006', userName: 'Frank Lee', userEmail: 'user@acme.com', accessLevel: 'read', addedAt: '2025-06-15T10:00:00Z', addedBy: 'usr_002' },
    ],
    lastPropagatedAt: '2026-03-15T06:00:00Z',
    propagationStatus: { targetCount: 3, confirmedCount: 2, failedCount: 0, status: 'complete' },
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'sc_002',
    name: 'Shared SFTP',
    connectorType: 'sftp',
    config: { host: 'sftp.acme.com', port: 22, basePath: '/shared' },
    ownerId: 'usr_001',
    ownerName: 'Alice Johnson',
    organizationId: 'org_001',
    sharedWith: [
      { userId: 'usr_002', userName: 'Bob Smith', userEmail: 'admin@acme.com', accessLevel: 'admin', addedAt: '2025-06-01T10:00:00Z', addedBy: 'usr_001' },
      { userId: 'usr_005', userName: 'Eve Martinez', userEmail: 'operator@acme.com', accessLevel: 'write', addedAt: '2025-06-01T10:00:00Z', addedBy: 'usr_001' },
    ],
    lastPropagatedAt: '2026-03-15T06:00:00Z',
    propagationStatus: { targetCount: 3, confirmedCount: 3, failedCount: 0, status: 'complete' },
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-12-01T10:00:00Z',
    isActive: true,
  },
];

export const mockSyncTemplates: SyncTemplate[] = [
  {
    id: 'st_001',
    name: 'Daily Backup Sync',
    description: 'Sync local project files to S3 daily',
    sourceConnector: 'local',
    sourcePath: '/projects',
    destConnector: 's3',
    destPath: 'acme-engineering/backups',
    syncMode: 'mirror',
    conflictResolution: 'newest_wins',
    fileFilters: ['*'],
    excludePatterns: ['node_modules', '.git', '*.tmp'],
    schedule: '0 2 * * *',
    organizationId: 'org_001',
    ownerId: 'usr_002',
    ownerName: 'Bob Smith',
    sharedWith: [
      { userId: 'usr_005', userName: 'Eve Martinez', userEmail: 'operator@acme.com', accessLevel: 'write', addedAt: '2025-07-01T10:00:00Z', addedBy: 'usr_002' },
    ],
    activatedByUsers: ['usr_002', 'usr_005'],
    propagationStatus: { targetCount: 2, confirmedCount: 2, failedCount: 0, status: 'complete' },
    createdAt: '2025-07-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
    isActive: true,
  },
];
